# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-05 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content_url', models.URLField()),
                ('p_date', models.DateField()),
                ('read_num', models.IntegerField()),
                ('like_num', models.IntegerField()),
                ('comment_num', models.IntegerField()),
                ('reward_num', models.IntegerField()),
                ('author', models.TextField()),
                ('source_url', models.URLField()),
                ('content', models.TextField()),
            ],
        ),
    ]
