# Generated by Django 2.2 on 2020-05-29 04:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guo', '0004_auto_20200529_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='M_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 29, 12, 1, 36, 241320), verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.BooleanField(null=True, verbose_name='性别'),
        ),
    ]
