# Generated by Django 2.2 on 2020-05-29 03:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guo', '0004_auto_20200529_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='M_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 29, 11, 3, 33, 749401), verbose_name='评论时间'),
        ),
    ]
