# Generated by Django 2.2 on 2020-06-01 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guo', '0006_auto_20200529_1215'),
        ('guo', '0004_auto_20200529_1116'),
        ('guo', '0005_auto_20200529_1103'),
        ('guo', '0002_auto_20200529_1127'),
    ]

    operations = [
    ]
