# Generated by Django 2.2 on 2020-05-29 01:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('guo', '0002_auto_20200529_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='M_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 29, 1, 38, 32, 996318, tzinfo=utc), verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='message',
            name='score',
            field=models.IntegerField(verbose_name='评分'),
        ),
    ]
