# Generated by Django 2.2 on 2020-05-29 03:13

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guo', '0002_auto_20200529_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='like',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL, verbose_name='喜欢的用户'),
        ),
        migrations.AlterField(
            model_name='message',
            name='M_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 29, 11, 13, 29, 257765), verbose_name='评论时间'),
        ),
    ]
