# Generated by Django 2.2 on 2020-05-29 03:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guo', '0003_auto_20200529_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='M_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 29, 11, 59, 33, 462085), verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.BooleanField(verbose_name='性别'),
        ),
    ]
