# Generated by Django 2.2 on 2020-06-01 16:31

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('guo', '0007_merge_20200601_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='com',
            field=models.CharField(max_length=200, null=True, verbose_name='公司'),
        ),
        migrations.AddField(
            model_name='game',
            name='pintai',
            field=models.CharField(max_length=200, null=True, verbose_name='运营平台'),
        ),
        migrations.AlterField(
            model_name='game',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='喜欢的用户'),
        ),
        migrations.AlterField(
            model_name='message',
            name='M_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='评论时间'),
        ),
    ]
