# Generated by Django 2.2.12 on 2020-06-03 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('guo', '0008_auto_20200601_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnveryEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='验证码')),
                ('start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
